// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

type Item struct {
	ID    int64
	Item  string
	Price float64
}

type Receipt struct {
	ID      int64
	ItemQty int64
	ItemID  int64
}

type ReceiptsUser struct {
	ReceiptID int64
	UserID    int64
}

type User struct {
	ID   int64
	Name string
}
